services:
  server:
    image: opensign/opensignserver:main
    restart: unless-stopped
    volumes:
      - opensign-files:/usr/src/app/files
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env.prod
    environment:
      NODE_ENV: production
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - data-volume:/data/db
    networks:
      - app-network

  client:
    image: opensign/opensign:main
    restart: unless-stopped
    depends_on:
      - server
    env_file: .env.prod
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  opensign-files:
